artifact_uri: file:D:/Tooth Pathology Project/Codes/runs/mlflow/859370485327238821/037fdc1ebb51428aaaad83a294d00e7b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '859370485327238821'
lifecycle_stage: active
run_id: 037fdc1ebb51428aaaad83a294d00e7b
run_name: train2
source_name: ''
source_type: 4
source_version: ''
start_time: 1766171184213
status: 1
tags: []
user_id: Anirudh
